# Generated by Django 6.0.7 on 2026-09-05 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Is public"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display order"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Tier",
                "verbose_name_plural": "Tiers",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TierVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="Version")),
                (
                    "effective_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Effective from"
                    ),
                ),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Effective until"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published at"
                    ),
                ),
                (
                    "configuration_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuration snapshot"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="eventyay_business.tier",
                        verbose_name="Tier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tier version",
                "verbose_name_plural": "Tier versions",
                "ordering": ["-version"],
                "unique_together": {("tier", "version")},
            },
        ),
        migrations.CreateModel(
            name="TierPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        max_length=20,
                        verbose_name="Billing interval",
                    ),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="Currency")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe price ID",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "tier_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="eventyay_business.tierversion",
                        verbose_name="Tier version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tier price",
                "verbose_name_plural": "Tier prices",
                "ordering": ["tier_version", "billing_interval", "currency"],
                "unique_together": {("tier_version", "billing_interval", "currency")},
            },
        ),
        migrations.CreateModel(
            name="TierEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capability",
                    models.CharField(max_length=100, verbose_name="Capability"),
                ),
                (
                    "value",
                    models.IntegerField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="Unit"),
                ),
                (
                    "overage_allowed",
                    models.BooleanField(default=False, verbose_name="Overage allowed"),
                ),
                (
                    "overage_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Overage price",
                    ),
                ),
                (
                    "overage_block_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Overage block size"
                    ),
                ),
                (
                    "tier_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="eventyay_business.tierversion",
                        verbose_name="Tier version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tier entitlement",
                "verbose_name_plural": "Tier entitlements",
                "ordering": ["tier_version", "capability"],
                "unique_together": {("tier_version", "capability")},
            },
        ),
    ]
