# Generated by Django 6.0.7 on 2026-09-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventyay_business', '0002_tierentitlement_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierentitlement',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Value'),
        ),
    ]
