# Generated by Django 6.0.7 on 2026-09-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventyay_business', '0003_alter_tierentitlement_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('billing_interval', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20, null=True, verbose_name='Billing interval')),
                ('currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Currency')),
                ('starts_at', models.DateTimeField(verbose_name='Starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Ends at')),
                ('cancel_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancel at')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe subscription ID')),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Configuration snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='base.organizer', verbose_name='Organizer')),
                ('tier_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='eventyay_business.tierversion', verbose_name='Tier version')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-starts_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'pending'])), fields=('organizer',), name='unique_active_subscription_per_organizer')],
            },
        ),
    ]
