# Generated by Django 6.0.7 on 2026-09-06 20:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
        ("eventyay_business", "0005_auto_assign_free_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capability",
                    models.CharField(max_length=100, verbose_name="Capability"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="Unit"),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Occurred at"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(max_length=100, verbose_name="Source type"),
                ),
                (
                    "source_id",
                    models.CharField(max_length=255, verbose_name="Source ID"),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=255, verbose_name="Idempotency key"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="base.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="base.organizer",
                        verbose_name="Organizer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage record",
                "verbose_name_plural": "Usage records",
                "ordering": ["-occurred_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organizer", "idempotency_key"),
                        name="unique_usage_idempotency_per_organizer",
                    )
                ],
            },
        ),
    ]
