# Generated by Django 6.0.7 on 2026-09-12 18:42

import django.db.models.deletion
from django.db import migrations, models


def backfill_past_due_since(apps, schema_editor):
    Subscription = apps.get_model("eventyay_business", "Subscription")
    from django.utils.timezone import now

    for sub in Subscription.objects.filter(
        status="past_due", past_due_since__isnull=True
    ):
        sub.past_due_since = sub.ends_at or now()
        sub.save(update_fields=["past_due_since"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventyay_business",
            "0013_tier_stripe_product_id_alter_eventaddon_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="past_due_since",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Past due since"
            ),
        ),
        migrations.RunPython(backfill_past_due_since, migrations.RunPython.noop),
        migrations.AddField(
            model_name="subscription",
            name="pending_billing_interval",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly"), ("annual", "Annual")],
                max_length=20,
                null=True,
                verbose_name="Pending billing interval",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="pending_change_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Pending change at"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="pending_tier_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_subscriptions",
                to="eventyay_business.tierversion",
                verbose_name="Pending tier version",
            ),
        ),
    ]
