# Generated by Django 6.0.7 on 2026-09-16 09:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0074_bbbserver_disable_ssl_janusserver_disable_ssl_and_more"),
        ("eventyay_business", "0014_subscription_past_due_since_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Invoice number"
                    ),
                ),
                (
                    "billing_period_start",
                    models.DateTimeField(verbose_name="Billing period start"),
                ),
                (
                    "billing_period_end",
                    models.DateTimeField(verbose_name="Billing period end"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("canceled", "Canceled"),
                            ("uncollectible", "Uncollectible"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Tax",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe payment intent ID",
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe invoice ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_invoices",
                        to="base.organizer",
                        verbose_name="Organizer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business invoice",
                "verbose_name_plural": "Business invoices",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BusinessInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription plan"),
                            ("addon", "Add-on package"),
                            ("platform_fee", "Platform ticket transaction fee"),
                            (
                                "registration_overage",
                                "Free ticket registration overage",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Line type",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Unit price",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "usage_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Usage reference",
                    ),
                ),
                (
                    "calculation_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Calculation metadata"
                    ),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eventyay_business.addondefinition",
                        verbose_name="Add-on",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_invoice_lines",
                        to="base.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="eventyay_business.businessinvoice",
                        verbose_name="Invoice",
                    ),
                ),
                (
                    "tier_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eventyay_business.tierversion",
                        verbose_name="Tier version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business invoice line",
                "verbose_name_plural": "Business invoice lines",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="businessinvoice",
            constraint=models.UniqueConstraint(
                fields=("organizer", "billing_period_start", "billing_period_end"),
                name="unique_business_invoice_period_per_organizer",
            ),
        ),
    ]
