# Generated by Django 6.0.7 on 2026-09-17 19:20

import django.core.validators
import django_countries.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventyay_business", "0015_businessinvoice_businessinvoiceline"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryFeeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Country"
                    ),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="Currency")),
                (
                    "service_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage fee applied to tickets for this country and currency.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Service fee percentage",
                    ),
                ),
                (
                    "maximum_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum fee limit in the specified currency. 0 indicates no maximum fee limit (unlimited).",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Maximum fee",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Country fee setting",
                "verbose_name_plural": "Country fee settings",
                "ordering": ["country", "currency"],
                "unique_together": {("country", "currency")},
            },
        ),
    ]
